#ifndef QTCMARKVIEW_GLOBAL_H
#define QTCMARKVIEW_GLOBAL_H

#include <QtGlobal>

#if defined(QTCMARKVIEW_LIBRARY)
#  define QTCMARKVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCMARKVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCMARKVIEW_GLOBAL_H

